// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Location struct {
	ID   string
	Name string
}

type Product struct {
	ID    string
	Name  string
	Image []byte
	Price float64
}

type Salon struct {
	ID   string
	Name string
}

type Table struct {
	ID        string
	Number    int64
	SalonID   string
	IsFull    int64
	TotalBill sql.NullFloat64
}

type TableProduct struct {
	TableID   string
	ProductID string
}

type User struct {
	ID       string
	FullName string
	Username string
	Password string
	Role     string
}
